version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - chatnet

  server1:
    build: .
    restart: always
    environment:
      - REDIS_HOST=redis
      - PORT=8000
    ports:
      - "8001:8000" # Maps Host Port 8001 -> Container Port 8000
    depends_on:
      - redis
    networks:
      - chatnet

  server2:
    build: .
    restart: always
    environment:
      - REDIS_HOST=redis
      - PORT=8000
    ports:
      - "8002:8000" # Maps Host Port 8002 -> Container Port 8000
    depends_on:
      - redis
    networks:
      - chatnet

networks:
  chatnet:
    driver: bridge